Config = {
  ui = {
    theme = 'catppuccin-mocha',
    border = 'rounded',
  },
  languages = {
    'vim',
    'lua',
    'json',
    'javascript',
    'typescript',
    'tsx',
    'go',
    'templ',
    'php',
    'css',
    'html',
    'yaml',
    'toml',
    'markdown',
  },
  lsp = {
    'lua_ls',
    'gopls',
    'templ',
    'tsserver',
    'astro',
    'pyright',
    'intelephense',
    'jsonls',
    'jqls',
  },
  keybind = {
    H = { '^', ' Goto first non-blank in line', noremap = true, silent = true },
    J = { ':m .+1<CR>==', ' Move line down', noremap = true, silent = true },
    K = { ':m .-2<CR>==', ' Move line up',  noremap = true, silent = true },
    L = { 'g_', ' Goto last non-blank in line', noremap = true, silent = true },
    Q = {
      name = '󰩈 Quit',
      Q = { ':q<cr>', '󰩈 Quit' },
      w = { ':wq<cr>', ' Write and Quit' },
      W = { ':wqa<cr>', ' Save all and quit' },
      f = { ':q!<cr>', ' Quit without saving' },
      F = { ':qa!<cr>', ' Quit all without saving' },
      a = { ':qa<cr>', '󱂬 Quit all' },
    },
    ['<leader>'] = {
      a = { vim.lsp.buf.code_action, ' Code Actions' },
      h = { vim.lsp.buf.hover, '󰼢 Hover tip' },
      r = { vim.lsp.buf.rename, '󰤀 Rename symbol' },
      y = { '"+y', ' Yank to system clipbboard' },
      p = { '"+p', ' Paste from system clipbboard' },
      c = { ':normal gcc<cr>', ' Toggle Comment' },
      b = {
        name = ' Buffers',
        b = { '<cmd>Telescope buffers<cr>', ' List Buffers' },
        n = { '<cmd>bnext<cr>', ' Next Buffer' },
        p = { '<cmd>bprevious<cr>', ' Previous Buffer' },
        c = { '<cmd>bd<cr>', ' Close Buffer' },
        k = { '<cmd>bn|bd#<cr>', '󰅙 Kill Buffer' },
        o = { '<cmd>lua Custom.close_other_buffers()<cr>', ' Close other buffers' },
      },
      f = {
        name = ' File',
        f = { '<cmd>Telescope find_files<cr>', '󰱽 Open File' },
        t = { '<cmd>Neotree float reveal_force_cwd<cr>', '󱏒 Tree Explorer' },
        n = { '<cmd>enew<cr>', ' New File' },
        r = { '<cmd>Telescope oldfiles<cr>', ' Recent Files' },
        h = { '<cmd>Telescope find_files hidden=true<cr>', '󰘓 Find Hidden Files' },
      },
      d = {
        name = '󰓙 Disgnotic',
        d = { '<cmd>Trouble diagnostics toggle<cr>', ' Open Diagnostics' },
        b = { '<cmd>Trouble diagnostics toggle filter.buf=0<cr>', '󱪘 Buffer Diagnostics' },
        l = { '<cmd>Trouble loclist toggle<cr>', ' Location List' },
        q = { '<cmd>Trouble qflist toggle<cr>', '󰁨 Quickfix List' },
        n = { '<cmd>TroubleNext<cr>', ' Next Diagnostic' },
        p = { '<cmd>TroublePrev<cr>', ' Previous Diagnostic' },
        a = { '<cmd>Trouble<cr>', ' All Diagnostics' },
      },
      s = {
        name = ' Search',
        s = { '/', ' Local Search', noremap = true, silent = false },
        c = { '<cmd>nohlsearch<cr>', '󰃢 Clear search results' },
        z = { '<cmd>Telescope current_buffer_fuzzy_find<cr>', '󰱽 Fuzzy find in current buffer', },
        f = { '<cmd>Telescope find_files<cr>', '󰱽 File Seach' },
        g = { '<cmd>Telescope live_grep<cr>', ' Global Search' },
        p = { '<cmd>Telescope lsp_document_symbols<cr>', ' Symbol Picker' },
        w = { '<cmd>Telescope lsp_dynamic_workspace_symbols<cr>', ' Workspace Symbol picker' },
        C = { '<cmd>Telescope command_history<cr>', ' Command History' },
        m = { '<cmd>Telescope marks<cr>', '󰟙 Marks' },
        a = { '<cmd>Telescope help_tags<cr>', ' Help Tags' },
      },
      g = {
        name = '󰦻 Goto',
        d = { '<cmd>Telescope lsp_definitions<cr>', ' Definition' },
        i = { '<cmd>Telescope lsp_implementations<cr>', '󰠲 Implementation' },
        r = { '<cmd>Telescope lsp_references<cr>', ' References' },
        w = { '<cmd>HopWord<cr>', ' Word' },
        l = { '<cmd>HopLine<cr>', ' Line' },
        c = { '<cmd>HopChar1<cr>', '󰾹 Char' },
        n = { '<cmd>HopNode<cr>', ' Node' },
        H = { '^', ' First non-blank in line', noremap = true, silent = true },
        L = { 'g_', ' Line end', noremap = true, silent = true },
        t = { 'gg', ' Top of file', noremap = true, silent = true },
        e = { 'G', ' End of file', noremap = true, silent = true },
      },
      G = {
        name = ' Git',
        G = { '<cmd>Neogit<cr>', '󰕴 Integrated Git UI' },
        b = { '<cmd>Telescope git_branches<cr>', ' Branches' },
        d = { '<cmd>DiffviewOpen<cr>', ' Diff view Open' },
        D = { '<cmd>DiffviewClose<cr>', ' Diff view Close' },
        h = { '<cmd>Gitsigns preview_hunk<cr>', '󰡫 Preview Hunk' },
        n = { '<cmd>Gitsigns next_hunk<cr>', ' Next Hunk' },
        N = { '<cmd>Gitsigns prev_hunk<cr>', ' Previous Hunk' },
        l = { '<cmd>Neogit log<cr>', ' Log' },
        p = { '<cmd>Gitsigns preview_hunk_inline<cr>', '󰆿 Preview Hunk Inline' },
        r = { '<cmd>Gitsigns reset_hunk<cr>', ' Reset Hunk' },
        s = { '<cmd>Telescope git_status<cr>', '󱖫 Status'},
      },
       w = {
        name = ' Window',
        w = { '<C-w>w', ' Switch window' },
        s = { '<cmd>split<cr><C-w>w', ' Horizontal Split' },
        v = { '<cmd>vsplit<cr><C-w>w', ' Vertical Split' },
        c = { '<cmd>close<cr>', ' Close Window' },
        h = { '<C-w>h', ' Move Left' },
        j = { '<C-w>j', ' Move Down' },
        k = { '<C-w>k', ' Move Up' },
        l = { '<C-w>l', ' Move Right' },
        m = { '<cmd>MaximizerToggle<cr>', '󰐃 Maximize Toggle' },
        e = { '<cmd>wincmd =<cr>', '󰖯 Equalize Window Sizes' },
      },
      ['?'] = { '<cmd>WhichKey<cr>', '󰓎 Show all commands' },
    },
  },
}

