Config = {
  ui = {
    --themes: default, catppuccin-mocha, catppuccin-macchiato, catppuccin-frappe, catppuccin-latte, dracula, dracula-soft, nord
    theme = "rose-pine-moon",
    border = "rounded", -- single, rounded, double
    indentRainbow = false,
    transparence = false,
    currentLineBlame = true,
  },
  keybind = {
    mode = { 'n', 'v' },
    { "<leader>?", "<cmd>WhichKey<cr>", desc = "󰓎 Show all commands" },
    { "<leader>/", "<cmd>nohlsearch<cr>", desc = "󰃢 Clear search selection" },
    { "<leader>a", vim.lsp.buf.code_action, desc = " Code Actions" },
    { "<leader>c", ":normal gcc<cr>", desc = " Toggle Comment" },
    { "<leader>e", "<cmd>Neotree float reveal_force_cwd<cr>", desc = "󱏒 Explore in file tree" },
    { "<leader>h", vim.lsp.buf.hover, desc = "󰼢 Hover tip" },
    { "<leader>y", '"+y', desc = " Yank to system clipbboard" },
    { "<leader>p", '"+p', desc = " Paste from system clipbboard" },
    { "<leader>r", vim.lsp.buf.rename, desc = "󰤀 Rename symbol" },
    { "<leader>s", ":w<cr>", desc = " Save" },
    { "J", ":m .+1<CR>==", desc = " Move line down", remap = false },
    { "K", ":m .-2<CR>==", desc = " Move line up", remap = false },
    { "H", "^", desc = " Goto first non-blank in line", remap = false },
    { "L", "g_", desc = " Goto last non-blank in line", remap = false },
    { "<leader>G", group = " Git" },
    { "<leader>GD", "<cmd>DiffviewClose<cr>", desc = " Diff view Close" },
    { "<leader>GG", "<cmd>Neogit<cr>", desc = "󰕴 Integrated Git UI" },
    { "<leader>GN", "<cmd>Gitsigns prev_hunk<cr>", desc = " Previous Hunk" },
    { "<leader>Gb", "<cmd>Telescope git_branches<cr>", desc = " Branches" },
    { "<leader>Gd", "<cmd>DiffviewOpen<cr>", desc = " Diff view Open" },
    { "<leader>Gh", "<cmd>Gitsigns preview_hunk<cr>", desc = "󰡫 Preview Hunk" },
    { "<leader>Gl", "<cmd>Neogit log<cr>", desc = " Log" },
    { "<leader>Gn", "<cmd>Gitsigns next_hunk<cr>", desc = " Next Hunk" },
    { "<leader>Gp", "<cmd>Gitsigns preview_hunk_inline<cr>", desc = "󰆿 Preview Hunk Inline" },
    { "<leader>Gr", "<cmd>Gitsigns reset_hunk<cr>", desc = " Reset Hunk" },
    { "<leader>Gs", "<cmd>Telescope git_status<cr>", desc = "󱖫 Status" },
    { "<leader>Gu", ":lua require('gitlinker').get_buf_range_url('n',{})<cr>", desc = " Copy remote URL" },
    { "<leader>b", group = " Buffers" },
    { "<leader>bb", "<cmd>Telescope buffers<cr>", desc = " List Buffers" },
    { "<leader>bc", "<cmd>bd<cr>", desc = " Close Buffer" },
    { "<leader>bk", "<cmd>bn|bd#<cr>", desc = "󰅙 Kill Buffer" },
    { "<leader>bn", "<cmd>bnext<cr>", desc = " Next Buffer" },
    { "<leader>bo", "<cmd>CloseOtherBuffers<cr>", desc = " Close other buffers" },
    { "<leader>d", group = " Debug" },
    { "<leader>db", "", desc = " Breakpoint" },
    { "<leader>dr", "", desc = " Run" },
    { "<leader>ds", "", desc = " Test" },
    { "<leader>ds", "", desc = " Stop" },
    { "<leader>D", group = "󰓙 Disgnotic" },
    { "<leader>Da", "<cmd>Trouble<cr>", desc = " All Diagnostics" },
    { "<leader>Db", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", desc = "󱪘 Buffer Diagnostics" },
    { "<leader>Dd", "<cmd>Trouble diagnostics toggle<cr>", desc = " Open Diagnostics" },
    { "<leader>Dl", "<cmd>Trouble loclist toggle<cr>", desc = " Location List" },
    { "<leader>Dn", "<cmd>TroubleNext<cr>", desc = " Next Diagnostic" },
    { "<leader>Dp", "<cmd>TroublePrev<cr>", desc = " Previous Diagnostic" },
    { "<leader>Dq", "<cmd>Trouble qflist toggle<cr>", desc = "󰁨 Quickfix List" },
    { "<leader>f", group = " Find" },
    { "<leader>fb", "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "󰩊 In Buffer" },
    { "<leader>fc", ':lua require"telescope.builtin".find_files({ hidden = true })<CR>', desc = " Command History" },
    { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "󰱽 Files" },
    { "<leader>fg", ':lua require"telescope.builtin".live_grep({ hidden = true })<cr>', desc = " Global" },
    { "<leader>fh", ':lua require"telescope.builtin".find_files({ hidden = true })<CR>', desc = "󰘓 Hidden Files" },
    { "<leader>fm", "<cmd>Telescope marks<cr>", desc = "󰟙 Marks" },
    { "<leader>fr", "<cmd>Telescope oldfiles<cr>", desc = " Recent Files" },
    { "<leader>ft", "<cmd>Telescope help_tags<cr>", desc = " Tags" },
    { "<leader>fw", "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", desc = " Workspace Symbol" },
    { "<leader>fs", "<cmd>Telescope lsp_document_symbols<cr>", desc = " Symbol" },
    { "<leader>g", group = "󰦻 Goto" },
    { "<leader>gH", "^", desc = " First non-blank in line", remap = false },
    { "gh", "^", desc = " First non-blank in line", remap = false },
    { "gl", "g_", desc = " Line end", remap = false },
    { "<leader>gc", "<cmd>HopChar1<cr>", desc = "󰾹 Char" },
    { "gd", "<cmd>Telescope lsp_definitions<cr>", desc = " Go to Definition" },
    { "<leader>gd", "<cmd>Telescope lsp_definitions<cr>", desc = " Definition" },
    { "<leader>ge", "G", desc = " End of file", remap = false },
    { "<leader>gi", "<cmd>Telescope lsp_implementations<cr>", desc = "󰠲 Implementation" },
    { "gI", "<cmd>Telescope lsp_implementations<cr>", desc = "󰠲 Go to Implementation" },
    { "<leader>gl", "<cmd>HopLine<cr>", desc = " Line" },
    { "<leader>gn", "<cmd>HopNode<cr>", desc = "󰉶 Node" },
    { "gr", "<cmd>Telescope lsp_references<cr>", desc = " Go to References" },
    { "<leader>gr", "<cmd>Telescope lsp_references<cr>", desc = " References" },
    { "<leader>gt", "gg", desc = " Top of file", remap = false },
    { "<leader>gw", "<cmd>HopWord<cr>", desc = " Word" },
    { "gw", "<cmd>HopWord<cr>", desc = " Go to Word" },
    { "<leader>m", group = "󰫙 Match" },
    { "<leader>mW", "viW", desc = " whole word" },
    { "<leader>mp", "vip", desc = " paragraph" },
    { "<leader>ms", "^vg_", desc = " sentense" },
    { "<leader>mt", "vat", desc = "󰅴 tag" },
    { "<leader>mw", "viw", desc = "󰾹 word" },
    { "<leader>w", group = " Window" },
    { "<leader>wc", "<cmd>close<cr>", desc = "󰅚 Close Window" },
    { "<leader>we", "<cmd>wincmd =<cr>", desc = "󰝘 Equalize Window Sizes" },
    { "<leader>wh", "<C-w>h", desc = " Move Left" },
    { "<leader>wj", "<C-w>j", desc = " Move Down" },
    { "<leader>wk", "<C-w>k", desc = " Move Up" },
    { "<leader>wl", "<C-w>l", desc = " Move Right" },
    { "<leader>wm", "<cmd>MaximizerToggle<cr>", desc = "󰆾 Maximize Toggle" },
    { "<leader>ws", "<cmd>split<cr><C-w>w", desc = " Horizontal Split" },
    { "<leader>wv", "<cmd>vsplit<cr><C-w>w", desc = " Vertical Split" },
    { "<leader>ww", "<C-w>w", desc = " Switch window" },
    { "Q", group = "󰩈 Quit" },
    { "QF", ":qa!<cr>", desc = " Quit all without saving" },
    { "QQ", ":q<cr>", desc = "󰩈 Quit" },
    { "QW", ":wqa<cr>", desc = " Save all and quit" },
    { "Qa", ":qa<cr>", desc = "󱂬 Quit all" },
    { "Qf", ":q!<cr>", desc = " Quit without saving" },
    { "Qw", ":wq<cr>", desc = " Write and Quit" },
  },
  signs = {
    Error = '',
    Warn = '󰔶',
    Hint = '󰝤',
    Information = '',
  },
  languages = {
    'vim',
    'lua',
    'json',
    'javascript',
    'typescript',
    'tsx',
    'go',
    'templ',
    'php',
    'css',
    'html',
    'yaml',
    'toml',
    'markdown',
    'kdl',
  },
  lsp = {
    'lua_ls',
    'gopls',
    'templ',
    'astro',
    'pyright',
    'intelephense',
    'jsonls',
    'jqls',
    biome = {
      root_dir = Utils.root_pattern("biome.json", "biome.jsonc"),
    },
    ts_ls = {
      root_dir = Utils.root_pattern("package.json"),
      single_file_support = false,
    },
    denols = {
      root_dir = Utils.root_pattern("deno.json", "deno.jsonc"),
    },
  },
}
