local ui = require("config.ui")

local keymap = {
  { "<Tab>",      "<cmd>bnext<cr>",                                          mode = { "n", "v" } },
  { "<S-Tab>",    "<cmd>bprevious<cr>",                                      mode = { "n", "v" } },
  { "<leader>t",  function() Snacks.terminal.toggle() end,                   desc = "Toggle Integrated Terminal",    icon = ui.symbols.modes["TERMINAL"] },
  { "<leader>,",  function() Snacks.dashboard() end,                         desc = "Show Dashboard",                icon = ui.symbols.commands.dashboard },
  { "<leader>?",  "<cmd>WhichKey<cr>",                                       desc = "Show all commands",             icon = ui.symbols.commands.which_key,               mode = { "n", "v" } },
  { "<leader>/",  "<cmd>nohlsearch<cr>",                                     desc = "Clear search selection",        icon = ui.symbols.commands.clear_search },
  { "<leader>a",  vim.lsp.buf.code_action,                                   desc = "Code Actions",                  icon = ui.symbols.commands.code_actions,            mode = { "n", "v" } },
  { "<leader>c",  ":normal gcc<cr>",                                         desc = "Toggle Comment",                icon = ui.symbols.commands.toggle_comment,          mode = { "n", "v" } },
  { "<leader>e",  function() Snacks.picker.explorer() end,                   desc = "Explore in file tree",          icon = ui.symbols.commands.file_tree },
  { "<leader>h",  vim.lsp.buf.hover,                                         desc = "Hover tip",                     icon = ui.symbols.commands.hover },
  { "<leader>y",  '"+y',                                                     desc = "Yank to system clipbboard",     icon = ui.symbols.commands.yank,                    mode = { "n", "v" } },
  { "<leader>p",  '"+p',                                                     desc = "Paste from system clipbboard",  icon = ui.symbols.commands.paste,                   mode = { "n", "v" } },
  { "<leader>r",  vim.lsp.buf.rename,                                        desc = "Rename symbol",                 icon = ui.symbols.commands.rename },
  { "<leader>s",  ":w<cr>",                                                  desc = "Save",                          icon = ui.symbols.commands.save },
  { "<leader>G",  group = "Git" },
  { "<leader>q",  ":q<cr>",                                                  desc = "Quit",                          icon = ui.symbols.commands.quit.quit },
  { "<leader>GG", function() Snacks.lazygit() end,                           desc = "Integrated Git UI",             icon = ui.symbols.git.logo },
  { "<leader>GN", "<cmd>Gitsigns prev_hunk<cr>",                             desc = "Previous Hunk",                 icon = ui.symbols.git.prev_hunk },
  { "<leader>Gb", function() Snacks.picker.git_branches() end,               desc = "Branches",                      icon = ui.symbols.git.branches },
  { "<leader>Gd", function() Snacks.picker.git_diff() end,                   desc = "Diff",                          icon = ui.symbols.git.diff_open },
  { "<leader>Gh", "<cmd>Gitsigns preview_hunk<cr>",                          desc = "Preview Hunk",                  icon = ui.symbols.git.preview_hunk },
  { "<leader>Gl", function() Snacks.picker.git_log() end,                    desc = "Log",                           icon = ui.symbols.git.log },
  { "<leader>Gn", "<cmd>Gitsigns next_hunk<cr>",                             desc = "Next Hunk",                     icon = ui.symbols.git.next_hunk },
  { "<leader>Gp", "<cmd>Gitsigns preview_hunk_inline<cr>",                   desc = "Preview Hunk Inline",           icon = ui.symbols.git.preview_hunk_inline },
  { "<leader>Gr", "<cmd>Gitsigns reset_hunk<cr>",                            desc = "Reset Hunk",                    icon = ui.symbols.git.reset_hunk },
  { "<leader>Gs", function() Snacks.picker.git_status() end,                 desc = "Status",                        icon = ui.symbols.git.status },
  { "<leader>Gu", ":lua require('gitlinker').get_buf_range_url('n',{})<cr>", desc = "Copy remote URL",               icon = ui.symbols.git.copy_url },
  { "<leader>b",  group = "Buffers",                                         icon = ui.symbols.commands.buffers.list },
  { "<leader>bb", function() Snacks.picker.buffers() end,                    desc = "List Buffers",                  icon = ui.symbols.commands.buffers.list },
  { "<leader>bc", "<cmd>bd<cr>",                                             desc = "Close Buffer",                  icon = ui.symbols.commands.buffers.close },
  { "<leader>bk", "<cmd>bn|bd#<cr>",                                         desc = "Kill Buffer",                   icon = ui.symbols.commands.buffers.kill },
  { "<leader>bn", "<cmd>bnext<cr>",                                          desc = "Next Buffer",                   icon = ui.symbols.commands.buffers.next },
  { "<leader>d",  group = "Debug" },
  { "<leader>db", "",                                                        desc = "Breakpoint",                    icon = ui.symbols.commands.debug.breakpoint },
  { "<leader>dr", "",                                                        desc = "Run",                           icon = ui.symbols.commands.debug.run },
  { "<leader>ds", "",                                                        desc = "Test",                          icon = ui.symbols.commands.debug.test },
  { "<leader>ds", "",                                                        desc = "Stop",                          icon = ui.symbols.commands.debug.stop },
  { "<leader>D",  group = "Diagnostics" },
  { "<leader>Da", "<cmd>Trouble<cr>",                                        desc = "All Diagnostics",               icon = ui.symbols.commands.diagnostic.all },
  { "<leader>Db", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",        desc = "Buffer Diagnostics",            icon = ui.symbols.commands.diagnostic.buffer },
  { "<leader>Dd", "<cmd>Trouble diagnostics toggle<cr>",                     desc = "Open Diagnostics",              icon = ui.symbols.commands.diagnostic.open },
  { "<leader>Dl", "<cmd>Trouble loclist toggle<cr>",                         desc = "Location List",                 icon = ui.symbols.commands.diagnostic.location_list },
  { "<leader>Dn", "<cmd>TroubleNext<cr>",                                    desc = "Next Diagnostic",               icon = ui.symbols.commands.diagnostic.next },
  { "<leader>Dp", "<cmd>TroublePrev<cr>",                                    desc = "Previous Diagnostic",           icon = ui.symbols.commands.diagnostic.prev },
  { "<leader>Dq", "<cmd>Trouble qflist toggle<cr>",                          desc = "Quickfix List",                 icon = ui.symbols.commands.diagnostic.quickfix },
  { "<leader>f",  group = "Find" },
  { "<leader>fb", function() Snacks.picker.grep_buffers() end,               desc = "In Open Buffers",               icon = ui.symbols.commands.find.buffer },
  { "<leader>fc", function() Snacks.picker.command_history() end,            desc = "Command History",               icon = ui.symbols.commands.find.command_history },
  { "<leader>ff", function() Snacks.picker.files() end,                      desc = "Files",                         icon = ui.symbols.commands.find.files },
  { "<leader>fg", function() Snacks.picker.grep() end,                       desc = "Global",                        icon = ui.symbols.commands.find.global },
  { "<leader>fh", function() Snacks.picker.files({ hidden = true }) end,     desc = "Hidden Files",                  icon = ui.symbols.commands.find.hidden },
  { "<leader>fm", function() Snacks.picker.marks() end,                      desc = "Marks",                         icon = ui.symbols.commands.find.marks },
  { "<leader>fr", function() Snacks.picker.recent() end,                     desc = "Recent Files",                  icon = ui.symbols.commands.find.recent },
  { "<leader>fs", function() Snacks.picker.lsp_symbols() end,                desc = "Symbol",                        icon = ui.symbols.commands.find.document_symbol },
  { "<leader>g",  group = "Goto",                                            icon = ui.symbols.commands.go_to.group },
  { "<leader>gH", "^",                                                       desc = "First non-blank in line",       icon = ui.symbols.commands.go_to.first_non_blank,   remap = false },
  { "<leader>gd", function() Snacks.picker.lsp_definitions() end,            desc = "Definition",                    icon = ui.symbols.commands.go_to.definition },
  { "<leader>gc", "<cmd>HopChar1<cr>",                                       desc = "Char",                          icon = ui.symbols.commands.go_to.char },
  { "<leader>ge", "G",                                                       desc = "End of file",                   icon = ui.symbols.commands.go_to.end_of_file,       remap = false },
  { "<leader>gi", function() Snacks.picker.lsp_implementations() end,        desc = "Implementation",                icon = ui.symbols.commands.go_to.implementation },
  { "<leader>gl", "<cmd>HopLine<cr>",                                        desc = "Line",                          icon = ui.symbols.commands.go_to.line },
  { "<leader>gn", "<cmd>HopNode<cr>",                                        desc = "Node",                          icon = ui.symbols.commands.go_to.node, },
  { "<leader>gr", function() Snacks.picker.lsp_references() end,             desc = "References",                    icon = ui.symbols.commands.go_to.references },
  { "<leader>gt", "gg",                                                      desc = "Top of file",                   icon = ui.symbols.commands.go_to.top_of_file,       remap = false },
  { "<leader>gw", "<cmd>HopWord<cr>",                                        desc = "Word",                          icon = ui.symbols.commands.go_to.word },
  { "<leader>m",  group = "Match",                                           icon = ui.symbols.commands.match.group },
  { "<leader>mW", "viW",                                                     desc = "whole word",                    icon = ui.symbols.commands.match.whole_word },
  { "<leader>mp", "vip",                                                     desc = "paragraph",                     icon = ui.symbols.commands.match.paragraph },
  { "<leader>ms", "^vg_",                                                    desc = "sentense",                      icon = ui.symbols.commands.match.sentence },
  { "<leader>mt", "vat",                                                     desc = "tag",                           icon = ui.symbols.commands.match.tag },
  { "<leader>mw", "viw",                                                     desc = "word",                          icon = ui.symbols.commands.match.word },
  { "<leader>w",  group = "Window" },
  { "<leader>wc", "<cmd>close<cr>",                                          desc = "Close Window",                  icon = ui.symbols.commands.window.close },
  { "<leader>we", "<cmd>wincmd =<cr>",                                       desc = "Equalize Window Sizes",         icon = ui.symbols.commands.window.equalize },
  { "<leader>wh", "<C-w>h",                                                  desc = "Move Left",                     icon = ui.symbols.commands.window.move_left },
  { "<leader>wj", "<C-w>j",                                                  desc = "Move Down",                     icon = ui.symbols.commands.window.move_down },
  { "<leader>wk", "<C-w>k",                                                  desc = "Move Up",                       icon = ui.symbols.commands.window.move_up },
  { "<leader>wl", "<C-w>l",                                                  desc = "Move Right",                    icon = ui.symbols.commands.window.move_right },
  { "<leader>wm", "<cmd>MaximizerToggle<cr>",                                desc = "Maximize Toggle",               icon = ui.symbols.commands.window.maximize },
  { "<leader>ws", "<cmd>split<cr><C-w>w",                                    desc = "Horizontal Split",              icon = ui.symbols.commands.window.horizontal_split },
  { "<leader>wv", "<cmd>vsplit<cr><C-w>w",                                   desc = "Vertical Split",                icon = ui.symbols.commands.window.vertical_split },
  { "<leader>ww", "<C-w>w",                                                  desc = "Switch window",                 icon = ui.symbols.commands.window.switch },
  { "<leader>u",  group = "UI" },
  { "<leader>ut", function() Snacks.picker.colorschemes() end,               desc = "Themes",                        icon = ui.symbols.commands.themes },
  { "<leader>uz", function() Snacks.zen() end,                               desc = "Toggle Zen Mode",               icon = ui.symbols.commands.zenmode },

  { "gh",         "^",                                                       desc = "First non-blank in line",       icon = ui.symbols.commands.go_to.first_non_blank,   remap = false,      mode = { "n", "v" } },
  { "gl",         "g_",                                                      desc = "Line end",                      icon = ui.symbols.commands.go_to.line,              remap = false,      mode = { "n", "v" } },
  { "gd",         function() Snacks.picker.lsp_definitions() end,            desc = "Go to Definition",              icon = ui.symbols.commands.go_to.definition },
  { "gD",         function() Snacks.picker.lsp_declarations() end,           desc = "Go to Declaration",             icon = ui.symbols.commands.go_to.definition },
  { "gi",         function() Snacks.picker.lsp_implementations() end,        desc = "Go to Implementation",          icon = ui.symbols.commands.go_to.implementation },
  { "gr",         function() Snacks.picker.lsp_references() end,             desc = "Go to References",              icon = ui.symbols.commands.go_to.references },
  { "gw",         "<cmd>HopWord<cr>",                                        desc = "Go to Word",                    icon = ui.symbols.commands.go_to.word },
  { "gt",         "gg",                                                      desc = "Top of file",                   icon = ui.symbols.commands.go_to.top_of_file,       remap = false },
  { "ge",         "G",                                                       desc = "End of file",                   icon = ui.symbols.commands.go_to.end_of_file,       remap = false },
  { "Q",          group = "Quit" },
  { "QF",         ":qa!<cr>",                                                desc = "Quit all without saving",       icon = ui.symbols.commands.quit.quit_all_force },
  { "QQ",         ":q<cr>",                                                  desc = "Quit",                          icon = ui.symbols.commands.quit.quit },
  { "QW",         ":wqa<cr>",                                                desc = "Save all and quit",             icon = ui.symbols.commands.quit.save_all_quit },
  { "Qa",         ":qa<cr>",                                                 desc = "Quit all",                      icon = ui.symbols.commands.quit.quit_all },
  { "Qf",         ":q!<cr>",                                                 desc = "Quit without saving",           icon = ui.symbols.commands.quit.quit_force },
  { "Qw",         ":wq<cr>",                                                 desc = "Write and Quit",                icon = ui.symbols.commands.quit.save_quit },
}

return keymap
